// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using td_revision.Models.EntityFramework;

#nullable disable

namespace td_revision.Migrations
{
    [DbContext(typeof(ProduitsbdContext))]
    [Migration("20250923200412_Changement_BD_RAILWAY")]
    partial class Changement_BD_RAILWAY
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("td_revision.Models.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idmarque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("IdMarque");

                    b.ToTable("marque");
                });

            modelBuilder.Entity("td_revision.Models.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idproduit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("idmarque");

                    b.Property<int?>("IdTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("idtypeproduit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("NomPhoto")
                        .HasColumnType("text")
                        .HasColumnName("nomPhoto");

                    b.Property<int?>("StockMaxi")
                        .HasColumnType("integer")
                        .HasColumnName("StockMaxi");

                    b.Property<int?>("StockMini")
                        .HasColumnType("integer")
                        .HasColumnName("stockMini");

                    b.Property<int?>("StockReel")
                        .HasColumnType("integer")
                        .HasColumnName("stockReel");

                    b.Property<string>("UrlPhoto")
                        .HasColumnType("text")
                        .HasColumnName("UrlPhoto");

                    b.HasKey("IdProduit");

                    b.HasIndex("IdMarque");

                    b.HasIndex("IdTypeProduit");

                    b.ToTable("produit");
                });

            modelBuilder.Entity("td_revision.Models.TypeProduit", b =>
                {
                    b.Property<int>("IdTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypeproduit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduit"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("IdTypeProduit");

                    b.ToTable("typeproduit");
                });

            modelBuilder.Entity("td_revision.Models.Produit", b =>
                {
                    b.HasOne("td_revision.Models.Marque", "MarqueProduitNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdMarque")
                        .HasConstraintName("FK_produits_marque");

                    b.HasOne("td_revision.Models.TypeProduit", "TypeProduitNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdTypeProduit")
                        .HasConstraintName("FK_produits_type_produit");

                    b.Navigation("MarqueProduitNavigation");

                    b.Navigation("TypeProduitNavigation");
                });

            modelBuilder.Entity("td_revision.Models.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("td_revision.Models.TypeProduit", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
