// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using td_revision.Models.EntityFramework;

#nullable disable

namespace td_revision.Migrations
{
    [DbContext(typeof(ProduitsbdContext))]
    partial class ProduitsbdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("td_revision.Models.Image", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idimage");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdImage"));

                    b.Property<int>("IdProduit")
                        .HasColumnType("integer")
                        .HasColumnName("idproduit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("urlphoto");

                    b.HasKey("IdImage");

                    b.HasIndex("IdProduit");

                    b.ToTable("t_e_image_img", (string)null);
                });

            modelBuilder.Entity("td_revision.Models.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idmarque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("IdMarque");

                    b.ToTable("t_e_marque_mrq", (string)null);
                });

            modelBuilder.Entity("td_revision.Models.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idproduit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("idmarque");

                    b.Property<int?>("IdTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("idtypeproduit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stockreel");

                    b.Property<int?>("StockMaxi")
                        .HasColumnType("integer")
                        .HasColumnName("stockmaxi");

                    b.Property<int?>("StockMini")
                        .HasColumnType("integer")
                        .HasColumnName("stockmini");

                    b.HasKey("IdProduit");

                    b.HasIndex("IdMarque");

                    b.HasIndex("IdTypeProduit");

                    b.ToTable("t_e_produit_prd", (string)null);
                });

            modelBuilder.Entity("td_revision.Models.TypeProduit", b =>
                {
                    b.Property<int>("IdTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypeproduit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduit"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("IdTypeProduit");

                    b.ToTable("t_e_typeproduit_typ", (string)null);
                });

            modelBuilder.Entity("td_revision.Models.Image", b =>
                {
                    b.HasOne("td_revision.Models.Produit", "ProduitNavigation")
                        .WithMany("Images")
                        .HasForeignKey("IdProduit")
                        .IsRequired()
                        .HasConstraintName("FK_t_e_image_img_t_e_produit_prd");

                    b.Navigation("ProduitNavigation");
                });

            modelBuilder.Entity("td_revision.Models.Produit", b =>
                {
                    b.HasOne("td_revision.Models.Marque", "MarqueProduitNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdMarque")
                        .HasConstraintName("FK_t_e_produit_prd_t_e_marque_mrq");

                    b.HasOne("td_revision.Models.TypeProduit", "TypeProduitNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdTypeProduit")
                        .HasConstraintName("FK_t_e_produit_prd_t_e_typeproduit_typ");

                    b.Navigation("MarqueProduitNavigation");

                    b.Navigation("TypeProduitNavigation");
                });

            modelBuilder.Entity("td_revision.Models.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("td_revision.Models.Produit", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("td_revision.Models.TypeProduit", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
